/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import javax.swing.*;

/**
 *
 * @author Fawzi
 */
public class login_signVue extends javax.swing.JFrame {

    /**
     * Creates new form login_sign
     */
    public login_signVue() {
        initComponents();
    }
    public void turn_off(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(false);
            }
        });
    }
    public void turn_on() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_erreur = new javax.swing.JDialog();
        err = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        p_switcher = new javax.swing.JPanel();
        h_login = new javax.swing.JPanel();
        l_login = new javax.swing.JLabel();
        h_sign = new javax.swing.JPanel();
        l_sign = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        p_container = new javax.swing.JPanel();
        login_page = new javax.swing.JPanel();
        login_l = new javax.swing.JLabel();
        p_username = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        p_password = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        p_login = new javax.swing.JPanel();
        login_b = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        sign_page = new javax.swing.JPanel();
        sign_btn = new javax.swing.JButton();
        p_nom = new javax.swing.JPanel();
        nom = new javax.swing.JTextField();
        p_cin = new javax.swing.JPanel();
        cin = new javax.swing.JTextField();
        p_email = new javax.swing.JPanel();
        email = new javax.swing.JTextField();
        p_re_pass = new javax.swing.JPanel();
        re_password = new javax.swing.JPasswordField();
        p_phone = new javax.swing.JPanel();
        phone = new javax.swing.JTextField();
        p_date = new javax.swing.JPanel();
        dateNaissance = new javax.swing.JTextField();
        p_adresse = new javax.swing.JPanel();
        Adresse = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        err.setText("login error");

        javax.swing.GroupLayout login_erreurLayout = new javax.swing.GroupLayout(login_erreur.getContentPane());
        login_erreur.getContentPane().setLayout(login_erreurLayout);
        login_erreurLayout.setHorizontalGroup(
            login_erreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_erreurLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(err)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        login_erreurLayout.setVerticalGroup(
            login_erreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_erreurLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(err)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(130, 204, 221));

        container.setBackground(new java.awt.Color(236, 243, 251));
        container.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        container.setLayout(new java.awt.BorderLayout());

        p_switcher.setBackground(new java.awt.Color(236, 243, 251));

        h_login.setBackground(new java.awt.Color(236, 243, 251));
        h_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                on_click(evt);
            }
        });

        l_login.setFont(new java.awt.Font("Open Sans Semibold", 1, 24)); // NOI18N
        l_login.setForeground(new java.awt.Color(9, 132, 227));
        l_login.setText("Login");

        javax.swing.GroupLayout h_loginLayout = new javax.swing.GroupLayout(h_login);
        h_login.setLayout(h_loginLayout);
        h_loginLayout.setHorizontalGroup(
            h_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, h_loginLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(l_login)
                .addGap(27, 27, 27))
        );
        h_loginLayout.setVerticalGroup(
            h_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(h_loginLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(l_login)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        h_sign.setBackground(new java.awt.Color(236, 243, 251));
        h_sign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                on_click(evt);
            }
        });

        l_sign.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        l_sign.setForeground(new java.awt.Color(87, 101, 116));
        l_sign.setText("Sign Up");

        javax.swing.GroupLayout h_signLayout = new javax.swing.GroupLayout(h_sign);
        h_sign.setLayout(h_signLayout);
        h_signLayout.setHorizontalGroup(
            h_signLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(h_signLayout.createSequentialGroup()
                .addComponent(l_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 363, Short.MAX_VALUE))
        );
        h_signLayout.setVerticalGroup(
            h_signLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(h_signLayout.createSequentialGroup()
                .addComponent(l_sign)
                .addGap(0, 56, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(87, 101, 116));
        jSeparator1.setForeground(new java.awt.Color(87, 101, 116));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_switcherLayout = new javax.swing.GroupLayout(p_switcher);
        p_switcher.setLayout(p_switcherLayout);
        p_switcherLayout.setHorizontalGroup(
            p_switcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_switcherLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238)
                .addComponent(h_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(h_sign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        p_switcherLayout.setVerticalGroup(
            p_switcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_switcherLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(p_switcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_switcherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(h_sign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_switcherLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        container.add(p_switcher, java.awt.BorderLayout.PAGE_START);

        p_container.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        p_container.setLayout(new java.awt.CardLayout());

        login_page.setBackground(new java.awt.Color(236, 243, 251));

        login_l.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/credit-card.png"))); // NOI18N

        p_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(236, 243, 251), 1, true));

        username.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        username.setForeground(new java.awt.Color(149, 165, 166));
        username.setText("Username");
        username.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_usernameLayout = new javax.swing.GroupLayout(p_username);
        p_username.setLayout(p_usernameLayout);
        p_usernameLayout.setHorizontalGroup(
            p_usernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        p_usernameLayout.setVerticalGroup(
            p_usernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        p_password.setPreferredSize(new java.awt.Dimension(98, 42));

        password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(149, 165, 166));
        password.setText("test");
        password.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_passwordLayout = new javax.swing.GroupLayout(p_password);
        p_password.setLayout(p_passwordLayout);
        p_passwordLayout.setHorizontalGroup(
            p_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(password)
        );
        p_passwordLayout.setVerticalGroup(
            p_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        login_b.setBackground(new java.awt.Color(41, 128, 185));
        login_b.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        login_b.setForeground(new java.awt.Color(255, 255, 255));
        login_b.setText("Login");
        login_b.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        login_b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_loginLayout = new javax.swing.GroupLayout(p_login);
        p_login.setLayout(p_loginLayout);
        p_loginLayout.setHorizontalGroup(
            p_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_loginLayout.createSequentialGroup()
                .addComponent(login_b, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p_loginLayout.setVerticalGroup(
            p_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 52, 54));
        jLabel2.setText("BoukiPay © Copyright 2021");

        javax.swing.GroupLayout login_pageLayout = new javax.swing.GroupLayout(login_page);
        login_page.setLayout(login_pageLayout);
        login_pageLayout.setHorizontalGroup(
            login_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_pageLayout.createSequentialGroup()
                .addGap(0, 440, Short.MAX_VALUE)
                .addComponent(p_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(531, 531, 531))
            .addGroup(login_pageLayout.createSequentialGroup()
                .addGroup(login_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_pageLayout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addComponent(login_l, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(login_pageLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addGroup(login_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(p_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(p_password, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)))
                    .addGroup(login_pageLayout.createSequentialGroup()
                        .addGap(427, 427, 427)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        login_pageLayout.setVerticalGroup(
            login_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_pageLayout.createSequentialGroup()
                .addComponent(login_l, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(p_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(p_password, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(p_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_container.add(login_page, "card2");

        sign_page.setBackground(new java.awt.Color(236, 243, 251));
        sign_page.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N

        sign_btn.setBackground(new java.awt.Color(41, 128, 185));
        sign_btn.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        sign_btn.setForeground(new java.awt.Color(255, 255, 255));
        sign_btn.setText("Registre");
        sign_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        p_nom.setFont(p_nom.getFont());

        nom.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        nom.setForeground(new java.awt.Color(149, 165, 166));
        nom.setText("Nom et prenom");
        nom.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        nom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomFocusLost(evt);
            }
        });
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_nomLayout = new javax.swing.GroupLayout(p_nom);
        p_nom.setLayout(p_nomLayout);
        p_nomLayout.setHorizontalGroup(
            p_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_nomLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_nomLayout.setVerticalGroup(
            p_nomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_nomLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cin.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        cin.setForeground(new java.awt.Color(149, 165, 166));
        cin.setText("CIN");
        cin.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        cin.setPreferredSize(new java.awt.Dimension(64, 40));
        cin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cinFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cinFocusLost(evt);
            }
        });
        cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_cinLayout = new javax.swing.GroupLayout(p_cin);
        p_cin.setLayout(p_cinLayout);
        p_cinLayout.setHorizontalGroup(
            p_cinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        p_cinLayout.setVerticalGroup(
            p_cinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        email.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        email.setForeground(new java.awt.Color(149, 165, 166));
        email.setText("Email");
        email.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_emailLayout = new javax.swing.GroupLayout(p_email);
        p_email.setLayout(p_emailLayout);
        p_emailLayout.setHorizontalGroup(
            p_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_emailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_emailLayout.setVerticalGroup(
            p_emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_emailLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        re_password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        re_password.setForeground(new java.awt.Color(149, 165, 166));
        re_password.setText("test");
        re_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        re_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                re_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                re_passwordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout p_re_passLayout = new javax.swing.GroupLayout(p_re_pass);
        p_re_pass.setLayout(p_re_passLayout);
        p_re_passLayout.setHorizontalGroup(
            p_re_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_re_passLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(re_password, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_re_passLayout.setVerticalGroup(
            p_re_passLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_re_passLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(re_password, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        phone.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        phone.setForeground(new java.awt.Color(149, 165, 166));
        phone.setText("Phone");
        phone.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });

        javax.swing.GroupLayout p_phoneLayout = new javax.swing.GroupLayout(p_phone);
        p_phone.setLayout(p_phoneLayout);
        p_phoneLayout.setHorizontalGroup(
            p_phoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_phoneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_phoneLayout.setVerticalGroup(
            p_phoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_phoneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dateNaissance.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        dateNaissance.setForeground(new java.awt.Color(149, 165, 166));
        dateNaissance.setText("yyyy-mm-dd");
        dateNaissance.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        dateNaissance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateNaissanceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dateNaissanceFocusLost(evt);
            }
        });

        javax.swing.GroupLayout p_dateLayout = new javax.swing.GroupLayout(p_date);
        p_date.setLayout(p_dateLayout);
        p_dateLayout.setHorizontalGroup(
            p_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_dateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_dateLayout.setVerticalGroup(
            p_dateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_dateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Adresse.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        Adresse.setForeground(new java.awt.Color(149, 165, 166));
        Adresse.setText("Adresse");
        Adresse.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        Adresse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AdresseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AdresseFocusLost(evt);
            }
        });
        Adresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdresseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_adresseLayout = new javax.swing.GroupLayout(p_adresse);
        p_adresse.setLayout(p_adresseLayout);
        p_adresseLayout.setHorizontalGroup(
            p_adresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Adresse, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        p_adresseLayout.setVerticalGroup(
            p_adresseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_adresseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 52, 54));
        jLabel1.setText("BoukiPay © Copyright 2021");

        javax.swing.GroupLayout sign_pageLayout = new javax.swing.GroupLayout(sign_page);
        sign_page.setLayout(sign_pageLayout);
        sign_pageLayout.setHorizontalGroup(
            sign_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sign_pageLayout.createSequentialGroup()
                .addGroup(sign_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sign_pageLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(sign_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(sign_pageLayout.createSequentialGroup()
                                .addGroup(sign_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(p_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(p_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(sign_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(p_cin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p_re_pass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(p_adresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(sign_pageLayout.createSequentialGroup()
                        .addGap(459, 459, 459)
                        .addGroup(sign_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sign_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(260, Short.MAX_VALUE))
        );
        sign_pageLayout.setVerticalGroup(
            sign_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sign_pageLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(sign_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_cin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(sign_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_re_pass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(sign_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(p_adresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(sign_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        p_container.add(sign_page, "card3");

        container.add(p_container, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        if(username.getText().equals("Username")){
            p_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9,132, 227), 1, true));

            username.setText("");
            username.setForeground(new java.awt.Color(20, 106, 168));
        }
    }//GEN-LAST:event_usernameFocusGained

    public JDialog getLogin_erreur() {
        return login_erreur;
    }

    public void setLogin_erreur(JDialog login_erreur) {
        this.login_erreur = login_erreur;
    }

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        p_username.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        if(username.getText().equals("")){
            username.setText("Username");
            username.setForeground(new java.awt.Color(149,165,166));
        }
    }//GEN-LAST:event_usernameFocusLost

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void login_bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_bActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        password.setForeground(new java.awt.Color(20, 106, 168));
     p_password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9,132, 227), 1, true));
        if(password.getText().equals("test")){
       password.setText("");
   }
    }//GEN-LAST:event_passwordFocusGained

    private void cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinActionPerformed

    private void nomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFocusGained
        if(nom.getText().equals("Nom et prenom")){
            p_nom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9,132, 227), 1, true));

            nom.setText("");
            nom.setForeground(new java.awt.Color(20, 106, 168));
        }
    }//GEN-LAST:event_nomFocusGained

    private void cinFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusGained
        if(cin.getText().equals("CIN")){
            p_cin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9,132, 227), 1, true));

            cin.setText("");
            cin.setForeground(new java.awt.Color(20, 106, 168));
        }
    }//GEN-LAST:event_cinFocusGained

    private void cinFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cinFocusLost
        p_cin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        if(cin.getText().equals("")){
            cin.setText("CIN");
            cin.setForeground(new java.awt.Color(149,165,166));
        }
    }//GEN-LAST:event_cinFocusLost

    private void nomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomFocusLost
        p_nom.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        if(nom.getText().equals("")){
            nom.setText("Nom et prenom");
            nom.setForeground(new java.awt.Color(149,165,166));
        }
    }//GEN-LAST:event_nomFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        if(email.getText().equals("Email")){
            p_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9,132, 227), 1, true));

            email.setText("");
            email.setForeground(new java.awt.Color(20, 106, 168));
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        p_email.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        if(email.getText().equals("")){
            email.setText("Email");
            email.setForeground(new java.awt.Color(149,165,166));
        }
    }//GEN-LAST:event_emailFocusLost

    private void re_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_re_passwordFocusGained
        if(re_password.getText().equals("test")){
            p_re_pass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9,132, 227), 1, true));

            re_password.setText("");
            re_password.setForeground(new java.awt.Color(20, 106, 168));
        }    }//GEN-LAST:event_re_passwordFocusGained

    private void re_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_re_passwordFocusLost
        p_re_pass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        if(re_password.getText().equals("")){
            re_password.setText("test");
            re_password.setForeground(new java.awt.Color(149,165,166));
        }    }//GEN-LAST:event_re_passwordFocusLost

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        if(phone.getText().equals("Phone")){
            p_phone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9,132, 227), 1, true));
            phone.setText("");
            phone.setForeground(new java.awt.Color(20, 106, 168));
        }    }//GEN-LAST:event_phoneFocusGained

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        p_phone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        if(phone.getText().equals("")){
            phone.setText("Phone");
            phone.setForeground(new java.awt.Color(149,165,166));
        }    }//GEN-LAST:event_phoneFocusLost

    private void dateNaissanceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateNaissanceFocusGained
        if(dateNaissance.getText().equals("yyyy-mm-dd")){
            p_date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9,132, 227), 1, true));

            dateNaissance.setText("");
            dateNaissance.setForeground(new java.awt.Color(20, 106, 168));
        }    }//GEN-LAST:event_dateNaissanceFocusGained

    private void dateNaissanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateNaissanceFocusLost
        p_date.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        if(dateNaissance.getText().equals("")){
            dateNaissance.setText("yyyy-mm-dd");
            dateNaissance.setForeground(new java.awt.Color(149,165,166));
        }
    }//GEN-LAST:event_dateNaissanceFocusLost

    private void AdresseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdresseFocusGained
        if(Adresse.getText().equals("Adresse")){
            p_adresse.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9,132, 227), 1, true));

            Adresse.setText("");
            Adresse.setForeground(new java.awt.Color(20, 106, 168));
        }     }//GEN-LAST:event_AdresseFocusGained

    private void AdresseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AdresseFocusLost
        p_adresse.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        if(Adresse.getText().equals("")){
            Adresse.setText("Adresse");
            Adresse.setForeground(new java.awt.Color(149,165,166));
        }    }//GEN-LAST:event_AdresseFocusLost

    private void AdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdresseActionPerformed

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
          p_password.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        if(password.getText().equals("")){
            password.setText("test");
            password.setForeground(new java.awt.Color(149,165,166));
        }       }//GEN-LAST:event_passwordFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // show a new form
                WelcomeVue form = new WelcomeVue();
                form.turn_on();
                this.turn_off();
                // close the current form(login form)
               // this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed



    private void on_click(java.awt.event.MouseEvent evt) {
        if(evt.getSource() ==h_login ){
            login_page.setVisible(true);
            sign_page.setVisible(false);
            l_login.setForeground(new java.awt.Color(9, 132, 227));
            l_sign.setForeground(new java.awt.Color(87, 101, 116));
        }
        else{
            login_page.setVisible(false);
            sign_page.setVisible(true);
            l_login.setForeground(new java.awt.Color(87, 101, 116));
            l_sign.setForeground(new java.awt.Color(9, 132, 227));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_signVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_signVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_signVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_signVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_signVue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adresse;
    private javax.swing.JTextField cin;
    private javax.swing.JPanel container;
    private javax.swing.JTextField dateNaissance;
    private javax.swing.JTextField email;
    private javax.swing.JLabel err;
    private javax.swing.JPanel h_login;
    private javax.swing.JPanel h_sign;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l_login;
    private javax.swing.JLabel l_sign;
    private javax.swing.JButton login_b;
    private javax.swing.JDialog login_erreur;
    private javax.swing.JLabel login_l;
    private javax.swing.JPanel login_page;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel p_adresse;
    private javax.swing.JPanel p_cin;
    private javax.swing.JPanel p_container;
    private javax.swing.JPanel p_date;
    private javax.swing.JPanel p_email;
    private javax.swing.JPanel p_login;
    private javax.swing.JPanel p_nom;
    private javax.swing.JPanel p_password;
    private javax.swing.JPanel p_phone;
    private javax.swing.JPanel p_re_pass;
    private javax.swing.JPanel p_switcher;
    private javax.swing.JPanel p_username;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phone;
    private javax.swing.JPasswordField re_password;
    private javax.swing.JButton sign_btn;
    private javax.swing.JPanel sign_page;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    public JTextField getAdresse() {
        return Adresse;
    }

    public void setAdresse(JTextField adresse) {
        Adresse = adresse;
    }

    public JTextField getCin() {
        return cin;
    }

    public void setCin(JTextField cin) {
        this.cin = cin;
    }

    public JPanel getContainer() {
        return container;
    }

    public void setContainer(JPanel container) {
        this.container = container;
    }

    public JTextField getDateNaissance() {
        return dateNaissance;
    }

    public void setDateNaissance(JTextField dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    public JTextField getEmail() {
        return email;
    }

    public void setEmail(JTextField email) {
        this.email = email;
    }

    public JPanel getH_login() {
        return h_login;
    }

    public void setH_login(JPanel h_login) {
        this.h_login = h_login;
    }

    public JPanel getH_sign() {
        return h_sign;
    }

    public void setH_sign(JPanel h_sign) {
        this.h_sign = h_sign;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getL_login() {
        return l_login;
    }

    public void setL_login(JLabel l_login) {
        this.l_login = l_login;
    }

    public JLabel getL_sign() {
        return l_sign;
    }

    public void setL_sign(JLabel l_sign) {
        this.l_sign = l_sign;
    }

    public JButton getLogin_b() {
        return login_b;
    }

    public void setLogin_b(JButton login_b) {
        this.login_b = login_b;
    }

    public JLabel getLogin_l() {
        return login_l;
    }

    public void setLogin_l(JLabel login_l) {
        this.login_l = login_l;
    }

    public JPanel getLogin_page() {
        return login_page;
    }

    public void setLogin_page(JPanel login_page) {
        this.login_page = login_page;
    }

    public JTextField getNom() {
        return nom;
    }

    public void setNom(JTextField nom) {
        this.nom = nom;
    }

    public JPanel getP_adresse() {
        return p_adresse;
    }

    public void setP_adresse(JPanel p_adresse) {
        this.p_adresse = p_adresse;
    }

    public JPanel getP_cin() {
        return p_cin;
    }

    public void setP_cin(JPanel p_cin) {
        this.p_cin = p_cin;
    }

    public JPanel getP_container() {
        return p_container;
    }

    public void setP_container(JPanel p_container) {
        this.p_container = p_container;
    }

    public JPanel getP_date() {
        return p_date;
    }

    public void setP_date(JPanel p_date) {
        this.p_date = p_date;
    }

    public JPanel getP_email() {
        return p_email;
    }

    public void setP_email(JPanel p_email) {
        this.p_email = p_email;
    }

    public JPanel getP_login() {
        return p_login;
    }

    public void setP_login(JPanel p_login) {
        this.p_login = p_login;
    }

    public JPanel getP_nom() {
        return p_nom;
    }

    public void setP_nom(JPanel p_nom) {
        this.p_nom = p_nom;
    }

    public JPanel getP_password() {
        return p_password;
    }

    public void setP_password(JPanel p_password) {
        this.p_password = p_password;
    }

    public JPanel getP_phone() {
        return p_phone;
    }

    public void setP_phone(JPanel p_phone) {
        this.p_phone = p_phone;
    }

    public JPanel getP_re_pass() {
        return p_re_pass;
    }

    public void setP_re_pass(JPanel p_re_pass) {
        this.p_re_pass = p_re_pass;
    }

    public JPanel getP_switcher() {
        return p_switcher;
    }

    public void setP_switcher(JPanel p_switcher) {
        this.p_switcher = p_switcher;
    }

    public JPanel getP_username() {
        return p_username;
    }

    public void setP_username(JPanel p_username) {
        this.p_username = p_username;
    }

    public JPasswordField getPassword() {
        return password;
    }

    public void setPassword(JPasswordField password) {
        this.password = password;
    }

    public JTextField getPhone() {
        return phone;
    }

    public void setPhone(JTextField phone) {
        this.phone = phone;
    }

    public JPasswordField getRe_password() {
        return re_password;
    }

    public void setRe_password(JPasswordField re_password) {
        this.re_password = re_password;
    }

    public JButton getSign_btn() {
        return sign_btn;
    }

    public void setSign_btn(JButton sign_btn) {
        this.sign_btn = sign_btn;
    }

    public JPanel getSign_page() {
        return sign_page;
    }

    public void setSign_page(JPanel sign_page) {
        this.sign_page = sign_page;
    }

    public JTextField getUsername() {
        return username;
    }

    public void setUsername(JTextField username) {
        this.username = username;
    }
}
