/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author hakim
 */
public class recharge_Mobile extends javax.swing.JFrame {

    /**
	 * initialize controller
	 */
	PaymentController controller= new PaymentController(this);

	private static final long serialVersionUID = 1L;
	/**
     * Creates new form recharge_Mobile
     */
    public recharge_Mobile() {
        initComponents();
    }
    
    public void turn_off(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(false);
            }
        });
    }
    public void turn_on() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        nTele = new javax.swing.JTextField();
        montant = new javax.swing.JComboBox<>();
        type_recharge = new javax.swing.JComboBox<>();
        rechargeButton = new javax.swing.JButton();
        rechargeButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		if(nTele.getText().equals("") || nTele.getText().equals("(06 (7) XX XX XX)"))
        		{
        			JOptionPane.showMessageDialog(jPanel1,"You have to write your number","Error",JOptionPane.ERROR_MESSAGE);
        		}else {
        			try {
        				String[] montantstr=montant.getSelectedItem().toString().split(" DH");
        				
						controller.payerRecharge(Integer.parseInt(montantstr[0]));
					} catch (Exception e1) {
						// TODO Auto-generated catch block
						e1.printStackTrace();
					}
        		}
        		
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 243, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(1064, 601));

        jPanel2.setBackground(new java.awt.Color(236, 243, 251));
        jPanel2.setForeground(new java.awt.Color(56, 103, 214));

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 103, 214));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recharge Mobile ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(291, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(112, 161, 255));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/smartphone.png"))); // NOI18N

        nTele.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        nTele.setForeground(new java.awt.Color(153, 153, 153));
        nTele.setText("(06 (7) XX XX XX)");
        nTele.setPreferredSize(new java.awt.Dimension(84, 28));
        nTele.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nTeleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nTeleFocusLost(evt);
            }
        });
        nTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nTeleActionPerformed(evt);
            }
        });

        montant.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        montant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10 DH", "20 DH", "25 DH", "30 DH", "50 DH", "100 DH", "200 DH", "500 DH" }));
        montant.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        montant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montantActionPerformed(evt);
            }
        });

        type_recharge.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        type_recharge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normale", "SMS *1", "Tous Compris *2", "Internet *3", "Resesux sociaux *6", "Internationale *8" }));
        type_recharge.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        type_recharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                type_rechargeActionPerformed(evt);
            }
        });

        rechargeButton.setBackground(new java.awt.Color(0, 84, 140));
        rechargeButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rechargeButton.setForeground(new java.awt.Color(255, 255, 255));
        rechargeButton.setText("Recharger");
        rechargeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rechargeButton.setMaximumSize(new java.awt.Dimension(93, 37));
        rechargeButton.setMinimumSize(new java.awt.Dimension(93, 37));
        rechargeButton.setPreferredSize(new java.awt.Dimension(93, 37));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(montant, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(type_recharge, 0, 779, Short.MAX_VALUE)
                    .addComponent(nTele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(120, 120, 120))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(rechargeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(50, 50, 50)
                .addComponent(nTele, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(montant, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(type_recharge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(rechargeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void montantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montantActionPerformed
        //action perform ...
        
        //get selected value from comboBox
        String selectedValue =montant.getSelectedItem().toString();
        /*
        // Now set this value from comboBox
        jTextField1.setText(selectedValue);
        */
    }//GEN-LAST:event_montantActionPerformed

    private void nTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nTeleActionPerformed

    private void nTeleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nTeleFocusGained
		nTele.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9,132, 227), 1, true));

    	if(nTele.getText().equals("(06 (7) XX XX XX)")){

            nTele.setText("");
            nTele.setForeground(new java.awt.Color(20, 106, 168));
        }
    }//GEN-LAST:event_nTeleFocusGained

    private void nTeleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nTeleFocusLost
         if(nTele.getText().equals("")){
             nTele.setText("(06 (7) XX XX XX)");
             nTele.setForeground(new java.awt.Color(149,165,166));
        }
         if(!nTele.getText().equals("") && !nTele.getText().equals("(06 (7) XX XX XX)") )
         {
        	 final String  regex = "^(06|07)[0-9]{8}$"; 

  		     Pattern pattern = Pattern.compile(regex);
  		     Matcher matcher = pattern.matcher(nTele.getText());
             if(!matcher.matches()) {
            	 nTele.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(187,33,36)));

     			JOptionPane.showMessageDialog(jPanel1,"NUMBER PHONE NOT VALIDE","Error",JOptionPane.INFORMATION_MESSAGE);

             }
         }
    }//GEN-LAST:event_nTeleFocusLost

    private void type_rechargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_type_rechargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_type_rechargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recharge_Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recharge_Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recharge_Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recharge_Mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recharge_Mobile().setVisible(true);
            }
        });
    }
    
    public void setErrorMessage(String errorMessage) {
        // lblErrorMessage.setText(errorMessage);
     	JOptionPane.showMessageDialog(jPanel1, errorMessage,"Error",JOptionPane.WARNING_MESSAGE);
     }
    
    public void setSuccesMessage(String succesMessage) {
        // lblErrorMessage.setText(errorMessage);
     	JOptionPane.showMessageDialog(jPanel1,succesMessage ,"Succes",JOptionPane.INFORMATION_MESSAGE);
     }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton rechargeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> montant;
    private javax.swing.JTextField nTele;
    private javax.swing.JComboBox<String> type_recharge;
    // End of variables declaration//GEN-END:variables
}
