/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetjava;

import javax.swing.*;

/**
 *
 * @author Fawzi
 */
public class WelcomeVue extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public WelcomeVue() {
        initComponents();
    }
    public void turn_off(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(false);
            }
        });
    }
    public void turn_on() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    public JLabel getBienvenue() {
        return bienvenue;
    }

    public void setBienvenue(JLabel bienvenue) {
        this.bienvenue = bienvenue;
    }

    public JPanel getContainer() {
        return container;
    }

    public void setContainer(JPanel container) {
        this.container = container;
    }

    public JLabel getIcon_bank() {
        return icon_bank;
    }

    public void setIcon_bank(JLabel icon_bank) {
        this.icon_bank = icon_bank;
    }

    public JLabel getIcon_card() {
        return icon_card;
    }

    public void setIcon_card(JLabel icon_card) {
        this.icon_card = icon_card;
    }

    public JLabel getjLabel1() {
        return copyright;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.copyright = jLabel1;
    }

    public JLabel getLogo() {
        return logo;
    }

    public void setLogo(JLabel logo) {
        this.logo = logo;
    }

    public JLabel getMotivation() {
        return motivation;
    }

    public void setMotivation(JLabel motivation) {
        this.motivation = motivation;
    }

    public JPanel getPay_card() {
        return pay_card;
    }

    public void setPay_card(JPanel pay_card) {
        this.pay_card = pay_card;
    }

    public JPanel getPay_compte() {
        return pay_compte;
    }

    public void setPay_compte(JPanel pay_compte) {
        this.pay_compte = pay_compte;
    }

    public JLabel getPayer_with() {
        return payer_with;
    }

    public void setPayer_with(JLabel payer_with) {
        this.payer_with = payer_with;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        bienvenue = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        motivation = new javax.swing.JLabel();
        payer_with = new javax.swing.JLabel();
        pay_compte = new javax.swing.JPanel();
        icon_bank = new javax.swing.JLabel();
        bank_btn = new javax.swing.JButton();
        pay_card = new javax.swing.JPanel();
        icon_card = new javax.swing.JLabel();
        cart_btn = new javax.swing.JButton();
        copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(236, 243, 251));
        container.setForeground(new java.awt.Color(44, 58, 71));
        container.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N

        bienvenue.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        bienvenue.setForeground(new java.awt.Color(48, 57, 82));
        bienvenue.setText("  Bienvenue sur");

        logo.setFont(new java.awt.Font("Open Sans", 1, 22)); // NOI18N
        logo.setForeground(new java.awt.Color(34, 112, 147));
        logo.setText("BoukiPay");

        motivation.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        motivation.setForeground(new java.awt.Color(44, 58, 71));
        motivation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        motivation.setText("Payer vos factures online facilement et 100% securise ");

        payer_with.setFont(new java.awt.Font("Open Sans", 0, 20)); // NOI18N
        payer_with.setText("Payer avec : ");

        pay_compte.setBackground(new java.awt.Color(183, 215, 250));
        pay_compte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 173, 169), 1, true));
        pay_compte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pay_compteMouseClicked(evt);
            }
        });

        icon_bank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_bank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/bank_64.png"))); // NOI18N

        bank_btn.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        bank_btn.setText("Votre Compte ");
        bank_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bank_btn.setContentAreaFilled(false);
        bank_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bank_btn.setFocusPainted(false);
        bank_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bank_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pay_compteLayout = new javax.swing.GroupLayout(pay_compte);
        pay_compte.setLayout(pay_compteLayout);
        pay_compteLayout.setHorizontalGroup(
            pay_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_bank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bank_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );
        pay_compteLayout.setVerticalGroup(
            pay_compteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay_compteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(icon_bank)
                .addGap(18, 18, 18)
                .addComponent(bank_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
        );

        pay_card.setBackground(new java.awt.Color(183, 215, 250));
        pay_card.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(56, 173, 169), 1, true));

        icon_card.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_card.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetjava/card_64.png"))); // NOI18N

        cart_btn.setFont(new java.awt.Font("Open Sans", 1, 20)); // NOI18N
        cart_btn.setText("Votre Carte");
        cart_btn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cart_btn.setContentAreaFilled(false);
        cart_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cart_btn.setFocusPainted(false);
        cart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cart_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pay_cardLayout = new javax.swing.GroupLayout(pay_card);
        pay_card.setLayout(pay_cardLayout);
        pay_cardLayout.setHorizontalGroup(
            pay_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_card, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cart_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );
        pay_cardLayout.setVerticalGroup(
            pay_cardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pay_cardLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(icon_card, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cart_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        copyright.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyright.setText("BoukiPay © Copyright 2021");

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(motivation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(333, 333, 333))
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(pay_compte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(pay_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(payer_with))
                .addContainerGap(179, Short.MAX_VALUE))
            .addComponent(copyright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bienvenue)
                    .addComponent(logo))
                .addGap(53, 53, 53)
                .addComponent(motivation)
                .addGap(72, 72, 72)
                .addComponent(payer_with)
                .addGap(32, 32, 32)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pay_card, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pay_compte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pay_compteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pay_compteMouseClicked

    }//GEN-LAST:event_pay_compteMouseClicked

    private void bank_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bank_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bank_btnActionPerformed

    private void cart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cart_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cart_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomeVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomeVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomeVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeVue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomeVue().setVisible(true);
            }
        });
    }

    public JButton getBank_btn() {
        return bank_btn;
    }

    public void setBank_btn(JButton bank_btn) {
        this.bank_btn = bank_btn;
    }

    public JButton getCart_btn() {
        return cart_btn;
    }

    public void setCart_btn(JButton cart_btn) {
        this.cart_btn = cart_btn;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bank_btn;
    private javax.swing.JLabel bienvenue;
    private javax.swing.JButton cart_btn;
    private javax.swing.JPanel container;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel icon_bank;
    private javax.swing.JLabel icon_card;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel motivation;
    private javax.swing.JPanel pay_card;
    private javax.swing.JPanel pay_compte;
    private javax.swing.JLabel payer_with;
    // End of variables declaration//GEN-END:variables
}
